const KEY='scout.scholarships.v2', $=s=>document.querySelector(s);
let rows=read();
function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('scout.scholarships.v1')||'[]');return Array.isArray(v)?v.map((x,i)=>({...x,id:x.id||`legacy-${i}`})):[]}catch{return[]}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0)}
function date(v){if(!v)return 'No date';return new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function daysLeft(v){return Math.ceil((new Date(`${v}T23:59:59`)-new Date())/86400000)}
function save(){localStorage.setItem(KEY,JSON.stringify(rows));render()}
function render(){
  const query=$('#search').value.trim().toLowerCase(),status=$('#filter').value,sort=$('#sort').value;
  const view=rows.filter(x=>(status==='all'||x.status===status)&&`${x.name} ${x.note}`.toLowerCase().includes(query));
  view.sort((a,b)=>sort==='amount'?(+b.amount||0)-(+a.amount||0):sort==='name'?a.name.localeCompare(b.name):(a.deadline||'9999').localeCompare(b.deadline||'9999'));
  const soon=rows.filter(x=>x.status!=='Submitted'&&x.status!=='Awarded'&&x.deadline&&daysLeft(x.deadline)>=0&&daysLeft(x.deadline)<=30).length;
  $('#stat-count').textContent=rows.length;$('#stat-value').textContent=money(rows.filter(x=>x.status!=='Not eligible').reduce((n,x)=>n+(+x.amount||0),0));$('#stat-soon').textContent=soon;$('#count').textContent=`${view.length} shown · ${rows.length} total`;
  $('#items').innerHTML=view.length?view.map(x=>{const d=x.deadline?daysLeft(x.deadline):null,link=safeUrl(x.url);const urgency=d!==null&&d<0?'Past due':d===0?'Due today':d!==null&&d<=7?`${d} days left`:d!==null?`${d} days left`:'No deadline';const klass=x.status==='Awarded'||x.status==='Submitted'?'green':d!==null&&d<=7?'amber':'';return `<article class="item"><div class="item-main"><div class="row wrap"><h3>${esc(x.name)}</h3><span class="pill ${klass}">${esc(x.status)}</span></div><div class="item-meta"><span class="pill">${x.amount?money(x.amount):'Amount not set'}</span><span class="pill ${d!==null&&d<=7?'amber':''}">${esc(urgency)} · ${date(x.deadline)}</span></div>${x.note?`<p>${esc(x.note)}</p>`:''}${link?`<p><a href="${esc(link)}" target="_blank" rel="noopener">Open official page ↗</a></p>`:''}<label class="field" style="max-width:170px;margin-top:10px">Update status<select data-status="${esc(x.id)}"><option ${x.status==='Considering'?'selected':''}>Considering</option><option ${x.status==='In progress'?'selected':''}>In progress</option><option ${x.status==='Submitted'?'selected':''}>Submitted</option><option ${x.status==='Awarded'?'selected':''}>Awarded</option><option ${x.status==='Not eligible'?'selected':''}>Not eligible</option></select></label></div><div class="item-actions"><button class="btn icon danger" data-remove="${esc(x.id)}" aria-label="Remove ${esc(x.name)}">×</button></div></article>`}).join(''):'<div class="empty"><strong>No matches yet</strong>Add an opportunity or adjust your search.</div>';